name: ccnewone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  google_nav_bar: ^5.0.6
    
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

assets:
  - lib/assets/tkm/
  - lib/assets/ads/
  - lib/assets/homeui/